a=str(input('se da primul cuvant:'))
b=str(input('se da al doilea cuvant:'))
c=str(input('se da al treilea cuvant:'))
d=str(input('se da al patrulea cuvant:'))
print(a)
print(b)
print(c)
print(d)
print(a+' '+b+' '+c+' '+d)